PORT: 5000
SERVER_URL: "http://localhost:5000"
CLIENT_URL : "google.com"

DB_PORT: "5432"
DB_HOST: "localhost"
DB_NAME: "testing"
DB_SSLMODE: "disable"
DB_USERNAME: "postgres"

EMAIL: lib.service@list.ru
SMTP_PORT: 465
SMTP_SERVER: smtp.mail.ru 

