PORT: 5000
SERVER_URL: "http://localhost:5000"
SERVER_DOMAIN: "localhost"
CLIENT_URL : "google.com"


DB_PORT: "5433"
DB_HOST: "95.140.159.168"
DB_NAME: "lib_service"
DB_SSLMODE: "disable"
DB_USERNAME: "go_project"

EMAIL: lib.service@list.ru
SMTP_PORT: 465
SMTP_SERVER: smtp.mail.ru 

